import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@/styles/themes.scss";
import ThemeSwitcher from "@/components/ThemeSwitcher/ThemeSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setThemeScript = `
    (function() {
      const savedTheme = document.cookie.match(/theme=([^;]*)/)?.[1];
      const theme = savedTheme || "dark";
      document.documentElement.setAttribute("data-theme", theme);
    })();
  `;

  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: setThemeScript }} />
      </head>
      <body>
        <header>
          <ThemeSwitcher />
        </header>
        {children}
      </body>
    </html>
  );
}
